name: Python Script Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 8-20 * * *" # At every 30th minute past every hour from 17 through 23 and every hour from 0 through 5.
  push:
    branches: [main]
jobs:
  run_script:
    runs-on: ubuntu-latest
    environment:
      name: env
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      AUTH_DATA: ${{ secrets.GCP_AUTH }}
      APP_MODE: ${{ vars.APP_MODE }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: initialize
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y curl && sudo apt-get clean
      - name: poetry repo
        run: sudo curl -sSL https://install.python-poetry.org/ | python -
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run Python script
        run: poetry run python3 webapp_aisekiya/app.py
      - name: Print environment variable
        run: echo ${{ vars.APP_MODE }}
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a || echo "No changes to commit"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
